name = "nourr-transport-website"
main = "public/index.html"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "echo 'No build required'"
watch_paths = ["public/**/*"]

[build.upload]
globs = ["public/**/*"]
ignore = ["public/node_modules/**/*"]
