name = "nourr-transport-website"
main = "public/index.html"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = ""
watch_paths = ["public/**/*"]

[[routes]]
pattern = "*"
zone_name = "example.com"
